import "../../styles/globals.css";
import { ApiProvider } from "./context/ApiProvider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <ApiProvider>{children}</ApiProvider>
      </body>
    </html>
  );
}
