# Development Docker Compose Override
# Usage: docker compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  # Development-specific backend configuration
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENVIRONMENT=development
    environment:
      # Override for development
      - DEBUG=true
      - DEV_MODE=true
      - LOG_LEVEL=DEBUG
      - ENVIRONMENT=development
      
      # Development CORS - allow all localhost ports
      - CORS_ORIGINS=["http://localhost:3000", "http://localhost:3001", "http://localhost:3002", "http://127.0.0.1:3000", "http://127.0.0.1:3001"]
      
      # Development database URLs (use Docker service names when running in Docker)
      - NEO4J_URI=${NEO4J_URI:-bolt://neo4j:7687}
      - PGVECTOR_DB_URL=${PGVECTOR_DB_URL:-postgresql://repolens:password@postgres:5432/vectordb}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
    
    # Development volumes - mount source code for hot reload
    volumes:
      - ./storage:/app/storage
      - ./.env:/app/.env:ro
      - ./app:/app/app:ro  # Mount source code for development
    
    # Remove health check dependencies for faster startup in dev
    depends_on: []
    
    # Development command with reload
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  # Development-specific database configurations
  neo4j:
    environment:
      # More permissive settings for development
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*,gds.*
      - NEO4J_dbms_memory_heap_initial__size=256m
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_dbms_memory_pagecache_size=512m

  postgres:
    environment:
      # Development-specific settings
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C --auth-host=scram-sha-256
    # Expose more ports for development tools
    ports:
      - "5433:5432"
      - "5434:5432"  # Alternative port for external tools

  redis:
    command: redis-server --appendonly yes --maxmemory 128mb --maxmemory-policy allkeys-lru
